name = "mauroesposito-cv"
pages_build_output_dir = "public"
compatibility_date = "2026-01-01"

[[d1_databases]]
binding = "DB"
database_name = "cv-db"
database_id = "f3c05f7a-b055-43f2-939a-8cb80c56b15f"
