CREATE TABLE IF NOT EXISTS content (
  section TEXT PRIMARY KEY,
  data TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS login_attempts (
  ip TEXT PRIMARY KEY,
  count INTEGER NOT NULL,
  first_attempt INTEGER NOT NULL
);
