// Regenerates migrations/0002_seed.sql from data/content.json.
// Run after editing data/content.json by hand: node scripts/generate-seed.js
const fs = require("fs");
const path = require("path");

const content = JSON.parse(fs.readFileSync(path.join(__dirname, "..", "data", "content.json"), "utf8"));

function sqlString(value) {
  return "'" + value.replace(/'/g, "''") + "'";
}

const lines = [
  "-- Generated by scripts/generate-seed.js from data/content.json. Do not edit by hand.",
  "DELETE FROM content;",
];
for (const [section, value] of Object.entries(content)) {
  lines.push(`INSERT INTO content (section, data) VALUES (${sqlString(section)}, ${sqlString(JSON.stringify(value))});`);
}

fs.writeFileSync(path.join(__dirname, "..", "migrations", "0002_seed.sql"), lines.join("\n") + "\n", "utf8");
console.log("Wrote migrations/0002_seed.sql");
